import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const translations = {
  en: {
    home: 'HOME',
    aboutUs: 'ABOUT US',
    offerings: 'OFFERINGS',
    financials: 'FINANCIALS',
    faq: 'FAQ',
    gallery: 'GALLERY',
    successStories: 'SUCCESS STORIES',
    careers: 'CAREERS',
    contactUs: 'CONTACT US',
    loginPortal: 'LOGIN FOR PMMY PORTAL',
    aboutMudra: 'About MUDRA',
    empoweringText: 'Empowering micro enterprises across India through accessible and affordable credit',
    messageFromLeadership: 'Message from Leadership',
    visionTitle: 'MUDRA VISION',
    missionTitle: 'MUDRA MISSION',
    loansDisbursed: 'Loans Disbursed',
    loansSanctioned: 'Loans Sanctioned',
    womenBeneficiaries: 'Women Beneficiaries',
    ofService: 'Of Service',

    // ---- Hero (HeroSection.jsx) ----
    heroBadge: 'GOVERNMENT OF INDIA INITIATIVE',
    heroTitle: '₹33,00,000+ Crore',
    heroSubtitle: 'Collateral-free MUDRA loans worth ₹33+ lakh crore disbursed',
    heroHighlight1: 'Funding the unfunded for ease of credit to Small businesses',
    heroHighlight2: '70% of beneficiaries are women entrepreneurs',
    heroCtaApply: 'Apply for a MUDRA Loan',
    heroCtaExplore: 'Explore Loan Schemes',
    heroStatDisbursed: 'Disbursed',
    heroStatLoans: 'Loans Sanctioned',
    heroStatWomen: 'Women Entrepreneurs',
    heroStatYears: 'Years of Impact',
    heroSlide2Title: '50+ Crore Loans',
    heroSlide2Subtitle: 'Over 50 crore loans sanctioned under PMMY since inception',
    heroSlide2Highlight1: 'Empowering micro enterprises across India',
    heroSlide2Highlight2: 'Supporting first-generation entrepreneurs',
    heroSlide3Title: '10 Years of MUDRA',
    heroSlide3Subtitle: 'Celebrating a decade of financial inclusion',
    heroSlide3Highlight1: 'Transforming lives through accessible credit',
    heroSlide3Highlight2: 'Building an entrepreneurial India',
    heroNews1: 'Borrowers are advised to keep away from persons posing as Agents/facilitators of MUDRA/PMMY',
    heroNews2: 'MUDRA is conducting Vigilance Awareness Week 2024',
    heroNews3: 'New online portal launched for easier loan applications',
    latestUpdates: 'Latest Updates',

    // ---- Impact Dashboard (ImpactDashboard.jsx) ----
    impactEyebrow: 'MUDRA IMPACT DASHBOARD',
    impactTitle: 'MUDRA Impact & Performance Statistics',
    impactDescription: "A decade of empowering grassroots micro enterprises, fostering self-employment, and bridging the formal financial credit gap across all 28 States and 8 Union Territories. Figures below are as published in MUDRA's official Financial Year statistical bulletins.",
    impactViewingFY: 'Viewing Financial Year',
    impactAmountSanctioned: 'Amount Sanctioned',
    impactAmountDisbursed: 'Amount Disbursed',
    impactLoansAccounts: 'Loans Sanctioned (Accounts)',
    impactUpdated: 'Updated',
    impactAllTime: 'All-Time',
    impactWomenBeneficiaries: 'Women Beneficiaries',
    impactWomenFootnote: 'Consistent across all published Financial Years',
    impactTrendChartTitle: 'Sanctioned & Disbursed Trend (₹ Crore) with Loan Volume',
    impactPublishedFYData: 'Published FY Data Points',
    impactTotalDisbursed: 'Total Disbursed (All-Time)',
    impactLoansSanctionedAllTime: 'Loans Sanctioned (All-Time)',
    impactNewEntrepreneurs: 'New Entrepreneurs',
    impactDemographicTitle: 'Demographic & Social Financial Reach',
    impactDemographicDesc: 'MUDRA loans prioritize social equity, ensuring priority sector lending reaches women, SC/ST, and rural micro-entrepreneurs.',
    impactDemoWomen: 'Women Entrepreneurs',
    impactDemoScSt: 'SC / ST / OBC Beneficiaries',
    impactDemoFirstTime: 'New / First-Time Borrowers',
    impactDemoRural: 'Rural & Semi-Urban Coverage',
    impactPanIndiaLabel: 'PMMY PAN-INDIA FOOTPRINT',
    impactPanIndiaTitle: '100% Coverage Across All 700+ Districts',
    impactPanIndiaDesc: 'MUDRA loans are accessible through 1,500+ Member Lending Institutions (Public Banks, RRBs, Cooperative Banks, MFIs, and NBFCs) connected via the Udyamimitra portal.',
    impactBulletinUpdated: 'Updated Statistical Bulletin 2024',
    impactDownloadReport: 'Download Report',

    // ---- Quick Links (QuickLinks.jsx) ----
    quickLinksEyebrow: 'RESOURCE HUB & DIRECTORY',
    quickLinksTitle: 'Essential Links & Official Reports',
    quickLinksDescription: 'Direct access to government refinancing portals, annual statistical data, scheme circulars, and official MSME publications.',
    quickLinksExploreDirectory: 'Explore Directory',
    quickLinksCatPortalsTitle: 'QUICK LINKS',
    quickLinksCatPortalsSubtitle: 'Institutional Portals',
    quickLinksCatPortalsDesc: 'Direct access to government refinancing portals, lending gateways, and rural credit networks.',
    quickLinksCatReportsTitle: 'PMMY REPORTS',
    quickLinksCatReportsSubtitle: 'Financial Performance',
    quickLinksCatReportsDesc: 'Audited financial progress statistics, state-wise loan disbursements, and MLI performance metrics.',
    quickLinksCatDocumentsTitle: 'DOCUMENTS',
    quickLinksCatDocumentsSubtitle: 'Official Publications',
    quickLinksCatDocumentsDesc: 'Official circulars, coffee table books, MSME policy frameworks, and success story compendiums.',
    quickLinksCatEventsTitle: 'EVENTS & MEDIA',
    quickLinksCatEventsSubtitle: 'Visual Highlights',
    quickLinksCatEventsDesc: 'Press bulletins, photo archives from national loan melas, and MSME award ceremonies.',

    // ---- About MUDRA (AboutPMMY.jsx) ----
    aboutEyebrow: 'WHOLLY OWNED SUBSIDIARY OF SIDBI',
    aboutTitle: 'About MUDRA & Pradhan Mantri MUDRA Yojana',
    aboutDescription: 'Micro Units Development & Refinance Agency Ltd. (MUDRA) was set up by the Government of India on April 8, 2015 to provide formal financial institution credit up to ₹20 Lakh to non-corporate, non-farm small and micro enterprises. MUDRA acts as a statutory refinancing bridge, empowering banks, MFIs, and NBFCs to extend collateral-free loans across India.',
    aboutPillar1Title: 'Refinance Assistance',
    aboutPillar1Desc: 'Provides low-cost refinancing support to Banks, MFIs, and NBFCs for last-mile credit flow to micro units.',
    aboutPillar2Title: 'Credit Guarantee Scheme',
    aboutPillar2Desc: 'Protects lending institutions through CGFMU guarantee cover to ensure collateral-free credit access.',
    aboutPillar3Title: 'MUDRA Card Facility',
    aboutPillar3Desc: 'Empowers borrowers with pre-approved working capital RuPay debit cards for hassle-free liquid credit withdrawals.',
    aboutPillar4Title: 'Capacity & Skill Development',
    aboutPillar4Desc: 'Partners with RSETIs and EDP institutes to train, mentor, and onboard first-generation entrepreneurs.',
    aboutStepLabel: 'Step',
    aboutStep1Title: 'MUDRA Refinances Member Lending Institutions',
    aboutStep1Desc: 'MUDRA, a wholly-owned subsidiary of SIDBI, provides low-cost refinance to Banks, MFIs, and NBFCs to on-lend to micro units.',
    aboutStep2Title: 'Member Lender Evaluates & Sanctions',
    aboutStep2Desc: 'The MLI assesses your business and disburses collateral-free credit across Shishu, Kishore & Tarun categories per PMMY guidelines.',
    aboutStep3Title: 'Credit Guarantee Protection (CGFMU)',
    aboutStep3Desc: 'Loans are backed by the Guarantee Fund for MUs, removing the need for third-party collateral or guarantee from borrowers.',
    aboutStep4Title: 'End-to-End Digital Access Across India',
    aboutStep4Desc: 'Borrowers apply via 1,500+ Member Lending Institutions connected through the Udyamimitra portal, covering 700+ districts.',

    // ---- Vision & Mission (VisionMission.jsx) ----
    visionMissionEyebrow: 'OUR GUIDING PHILOSOPHY',
    visionMissionTitlePrefix: 'Vision & Mission of',
    visionMissionDescription: 'Building an inclusive, resilient financial ecosystem that fosters micro-entrepreneurship and economic self-reliance across India.',
    visionKicker: 'STRATEGIC OUTLOOK',
    visionTag: 'Future Benchmark',
    visionQuote: '"To be an integrated financial and support services provider par excellence benchmarked with global best practices and standards for the bottom of the pyramid universe for their comprehensive economic and social development."',
    visionPillarsLabel: 'Key Vision Drivers:',
    visionPillar1: 'Integrated Financial Services',
    visionPillar2: 'Global Best Practices',
    visionPillar3: 'Bottom of Pyramid Support',
    visionPillar4: 'Comprehensive Social Growth',
    visionFooterLeft: 'National Standard',
    visionFooterRight: 'Bottom of Pyramid Focus',
    missionKicker: 'ACTION OBJECTIVE',
    missionTag: 'Institutional Synergy',
    missionQuote: '"To create an inclusive, sustainable and value based entrepreneurial culture, in collaboration with our partner institutions in achieving economic success and financial security."',
    missionPillarsLabel: 'Key Mission Pillars:',
    missionPillar1: 'Inclusive Enterprise Culture',
    missionPillar2: 'Partner Institution Synergy',
    missionPillar3: 'Sustainable Financial Security',
    missionPillar4: 'Value-Based Empowerment',
    missionFooterLeft: 'Partner Institutions',
    missionFooterRight: 'Financial Security',

    // ---- Loan Products (LoanProducts.jsx) ----
    loanProductsEyebrow: 'CATEGORIZED CREDIT CATEGORIES',
    loanProductsTitle: 'PMMY Schemes Overview & Categories',
    loanProductsDescription: 'MUDRA classifies loans into four tailored categories. Click on any scheme card to open complete eligibility, interest rates, required documents, and application info.',
    loanProductsCollateralFree: 'Collateral-Free PMMY Credit Facility',
    loanProductsViewInfo: 'Click to View Info & Apply',
    loanProductShishuStage: 'Startups & Micro Beginners',
    loanProductShishuRange: 'Loans up to ₹50,000/-',
    loanProductShishuDesc: 'Designed for early-stage micro entrepreneurs, small artisans, street vendors, and shopkeepers setting up initial business operations.',
    loanProductKishoreStage: 'Growing Micro Units',
    loanProductKishoreRange: 'Above ₹50k & Up to ₹5 Lakh',
    loanProductKishoreDesc: 'Ideal for existing business owners seeking working capital, machinery purchase, inventory expansion, or business modernization.',
    loanProductTarunStage: 'Established Enterprises',
    loanProductTarunRange: 'Above ₹5 Lakh & Up to ₹10 Lakh',
    loanProductTarunDesc: 'Tailored for established small businesses expanding operations, upgrading technology, scaling trade volume, or buying commercial vehicles.',
    loanProductTarunPlusStage: 'Repeat Track Record Borrowers',
    loanProductTarunPlusRange: 'Above ₹10 Lakh & Up to ₹20 Lakh',
    loanProductTarunPlusDesc: 'Union Budget MUDRA 2.0 initiative doubling the limit for repeat borrowers who have successfully repaid previous Tarun loans with pristine record.',

    // ---- Loan Journey (LoanJourney.jsx) ----
    loanJourneyEyebrow: 'YOUR MUDRA JOURNEY',
    loanJourneyTitle: 'From Discovery to Disbursement — Guided Every Step',
    loanJourneyDescription: 'A single, connected path from checking eligibility to tracking your sanctioned loan — each step links directly to the relevant MUDRA service.',
    loanJourneyStep1Title: 'Check Eligibility',
    loanJourneyStep1Desc: 'Review the eligibility, loan limits and required documents for Shishu, Kishore, Tarun and TarunPlus.',
    loanJourneyStep1Cta: 'View Eligibility',
    loanJourneyStep2Title: 'Select a Scheme',
    loanJourneyStep2Desc: 'Compare the four PMMY categories and pick the one that matches your business stage.',
    loanJourneyStep2Cta: 'Compare Schemes',
    loanJourneyStep3Title: 'Apply',
    loanJourneyStep3Desc: 'Start the guided onboarding, or apply directly through the official JanSamarth portal.',
    loanJourneyStep3Cta: 'Start Application',
    loanJourneyStep3SecondaryCta: 'Apply via JanSamarth',
    loanJourneyStep4Title: 'Track Application',
    loanJourneyStep4Desc: 'Follow your application status, validations and disbursement in real time.',
    loanJourneyStep4Cta: 'Track Status',

    // ---- Success Stories Carousel (SuccessStoriesCarousel.jsx) ----
    successCarouselEyebrow: 'GRASSROOTS INSPIRATION',
    successCarouselTitle: 'PMMY Success Stories',
    successCarouselDescription: 'Real stories of grassroots entrepreneurs, women leaders, and rural innovators empowered by collateral-free MUDRA loans. Hover a card to read the story.',
    successCarouselExploreAll: 'Explore All Stories',
    successCarouselReadFull: 'Read Full Story',
    successCarouselImpact: 'Impact',

    // ---- Fraud & Safety Center (FraudSafetyCenter.jsx) ----
    fraudEyebrow: 'FRAUD & SAFETY CENTER',
    fraudTitle: 'Stay Safe — MUDRA Never Charges Through Agents',
    fraudDescription: "Official statutory advisory for every PMMY applicant. If you're ever asked for payment by someone claiming to represent MUDRA, it is fraudulent.",
    fraudSafeguard1Title: 'No Agents or Middlemen',
    fraudSafeguard1Desc: 'MUDRA has NOT engaged any agents or facilitators. Beware of fraudulent impostors posing as official MUDRA representatives.',
    fraudSafeguard2Title: 'Apply Only Through Official Channels',
    fraudSafeguard2Desc: 'MUDRA is a refinancing institution and does not lend directly to individuals. Borrowers can apply via Member Lending Institutions (Banks, MFIs, NBFCs) or online through the official Udyamimitra portal.',
    fraudSafeguard3Title: 'Never Pay Processing Fees to Individuals',
    fraudSafeguard3Desc: 'Borrowers are strictly advised not to pay any money or processing fees to individuals posing as official MUDRA facilitators.',
    fraudReportLabel: 'Suspect Fraud? Report It Immediately',
    fraudReportDesc: "Contact the official helpdesk or toll-free helpline below, or reach out via the Contact page — do not engage with anyone demanding payment on MUDRA's behalf.",
    fraudReportCta: 'Report Fraud',

    // ---- Announcements & News (AnnouncementsNews.jsx) ----
    newsEyebrow: 'OFFICIAL BULLETIN & NOTIFICATIONS',
    newsTitle: 'Announcements & Latest News',
    newsDescription: 'Stay informed with official press releases, government circulars, statutory vigilance alerts, and policy guidelines directly from MUDRA.',
    newsTabPress: 'Press News',
    newsTabCirculars: 'Official Circulars',
    newsTabAdvisories: 'Statutory Advisories',
    newsAdvisoryLabel: 'Statutory Advisory:',
    newsAdvisoryText: 'MUDRA does NOT charge any upfront processing fee nor engage middle agents. Always apply directly via Banks or the JanSamarth portal',
    newsReadCircular: 'Read Circular',

    // ---- Social Media Feed (SocialMediaFeed.jsx) ----
    socialEyebrow: 'REAL-TIME SOCIAL CONNECT',
    socialTitle: 'MUDRA Live Social Media Hub',
    socialDescription: 'Stay updated with official announcements, videos, success stories & policy updates directly from MUDRA India verified social channels.',
    socialTabAll: 'All Feeds',
    socialTrendingTopics: 'Trending Topics:',
    socialClearFilter: 'Clear Filter',
    socialNoPosts: 'No posts match the selected filters.',
    socialViewPost: 'View Post',
  },
  hi: {
    home: 'मुख्य पृष्ठ',
    aboutUs: 'हमारे बारे में',
    offerings: 'योजनाएं',
    financials: 'वित्तीय',
    faq: 'सामान्य प्रश्न',
    gallery: 'गैलरी',
    successStories: 'सफलता की कहानियां',
    careers: 'करियर',
    contactUs: 'संपर्क करें',
    loginPortal: 'PMMY पोर्टल लॉगिन',
    aboutMudra: 'मुद्रा के बारे में',
    empoweringText: 'सुलभ और किफायती ऋण के माध्यम से भारत भर में सूक्ष्म उद्यमों को सशक्त बनाना',
    messageFromLeadership: 'नेतृत्व से संदेश',
    visionTitle: 'मुद्रा दृष्टिकोण',
    missionTitle: 'मुद्रा मिशन',
    loansDisbursed: 'वितरित ऋण',
    loansSanctioned: 'स्वीकृत ऋण',
    womenBeneficiaries: 'महिला लाभार्थी',
    ofService: 'सेवा के वर्ष',

    // ---- Hero (HeroSection.jsx) ----
    heroBadge: 'भारत सरकार की पहल',
    heroTitle: '₹33,00,000+ करोड़',
    heroSubtitle: 'बिना जमानत के ₹33+ लाख करोड़ के मुद्रा ऋण वितरित',
    heroHighlight1: 'छोटे व्यवसायों को आसान ऋण उपलब्ध कराना',
    heroHighlight2: '70% लाभार्थी महिला उद्यमी हैं',
    heroCtaApply: 'मुद्रा ऋण के लिए आवेदन करें',
    heroCtaExplore: 'ऋण योजनाएं देखें',
    heroStatDisbursed: 'वितरित राशि',
    heroStatLoans: 'स्वीकृत ऋण',
    heroStatWomen: 'महिला उद्यमी',
    heroStatYears: 'वर्षों का प्रभाव',
    heroSlide2Title: '50+ करोड़ ऋण',
    heroSlide2Subtitle: 'शुरुआत से अब तक PMMY के तहत 50 करोड़ से अधिक ऋण स्वीकृत',
    heroSlide2Highlight1: 'पूरे भारत में सूक्ष्म उद्यमों को सशक्त बनाना',
    heroSlide2Highlight2: 'प्रथम पीढ़ी के उद्यमियों को सहयोग',
    heroSlide3Title: 'मुद्रा के 10 वर्ष',
    heroSlide3Subtitle: 'वित्तीय समावेशन के एक दशक का उत्सव',
    heroSlide3Highlight1: 'सुलभ ऋण से जीवन में बदलाव',
    heroSlide3Highlight2: 'एक उद्यमशील भारत का निर्माण',
    heroNews1: 'ऋण लेने वाले मुद्रा/PMMY के एजेंट या सुविधाकर्ता बताने वाले व्यक्तियों से सावधान रहें',
    heroNews2: 'मुद्रा सतर्कता जागरूकता सप्ताह 2024 का आयोजन कर रही है',
    heroNews3: 'आसान ऋण आवेदन के लिए नया ऑनलाइन पोर्टल लॉन्च',
    latestUpdates: 'ताज़ा अपडेट',

    // ---- Impact Dashboard (ImpactDashboard.jsx) ----
    impactEyebrow: 'मुद्रा प्रभाव डैशबोर्ड',
    impactTitle: 'मुद्रा प्रभाव और प्रदर्शन आंकड़े',
    impactDescription: 'सभी 28 राज्यों और 8 केंद्र शासित प्रदेशों में जमीनी स्तर के सूक्ष्म उद्यमों को सशक्त बनाने, स्वरोजगार को बढ़ावा देने और औपचारिक वित्तीय ऋण अंतर को पाटने का एक दशक। नीचे दिए गए आंकड़े मुद्रा के आधिकारिक वित्त वर्ष सांख्यिकीय बुलेटिन में प्रकाशित अनुसार हैं।',
    impactViewingFY: 'वित्त वर्ष देख रहे हैं',
    impactAmountSanctioned: 'स्वीकृत राशि',
    impactAmountDisbursed: 'वितरित राशि',
    impactLoansAccounts: 'स्वीकृत ऋण (खाते)',
    impactUpdated: 'अद्यतन',
    impactAllTime: 'सर्वकालिक',
    impactWomenBeneficiaries: 'महिला लाभार्थी',
    impactWomenFootnote: 'सभी प्रकाशित वित्त वर्षों में सुसंगत',
    impactTrendChartTitle: 'स्वीकृत और वितरित रुझान (₹ करोड़) एवं ऋण मात्रा',
    impactPublishedFYData: 'प्रकाशित वित्त वर्ष आंकड़े',
    impactTotalDisbursed: 'कुल वितरित (सर्वकालिक)',
    impactLoansSanctionedAllTime: 'स्वीकृत ऋण (सर्वकालिक)',
    impactNewEntrepreneurs: 'नए उद्यमी',
    impactDemographicTitle: 'जनसांख्यिकीय एवं सामाजिक वित्तीय पहुंच',
    impactDemographicDesc: 'मुद्रा ऋण सामाजिक समानता को प्राथमिकता देते हैं, जिससे प्राथमिकता क्षेत्र ऋण महिलाओं, अनुसूचित जाति/जनजाति और ग्रामीण सूक्ष्म-उद्यमियों तक पहुंचता है।',
    impactDemoWomen: 'महिला उद्यमी',
    impactDemoScSt: 'अनुसूचित जाति/जनजाति/अन्य पिछड़ा वर्ग लाभार्थी',
    impactDemoFirstTime: 'नए / प्रथम बार के ऋणी',
    impactDemoRural: 'ग्रामीण एवं अर्ध-शहरी कवरेज',
    impactPanIndiaLabel: 'PMMY अखिल भारतीय उपस्थिति',
    impactPanIndiaTitle: 'सभी 700+ जिलों में 100% कवरेज',
    impactPanIndiaDesc: 'मुद्रा ऋण उद्यमीमित्र पोर्टल से जुड़े 1,500+ सदस्य ऋणदाता संस्थानों (सार्वजनिक बैंक, RRB, सहकारी बैंक, MFI और NBFC) के माध्यम से उपलब्ध हैं।',
    impactBulletinUpdated: 'अद्यतन सांख्यिकीय बुलेटिन 2024',
    impactDownloadReport: 'रिपोर्ट डाउनलोड करें',

    // ---- Quick Links (QuickLinks.jsx) ----
    quickLinksEyebrow: 'संसाधन केंद्र एवं निर्देशिका',
    quickLinksTitle: 'महत्वपूर्ण लिंक एवं आधिकारिक रिपोर्ट',
    quickLinksDescription: 'सरकारी पुनर्वित्त पोर्टल, वार्षिक सांख्यिकीय आंकड़ों, योजना परिपत्रों और आधिकारिक MSME प्रकाशनों तक सीधी पहुंच।',
    quickLinksExploreDirectory: 'निर्देशिका देखें',
    quickLinksCatPortalsTitle: 'त्वरित लिंक',
    quickLinksCatPortalsSubtitle: 'संस्थागत पोर्टल',
    quickLinksCatPortalsDesc: 'सरकारी पुनर्वित्त पोर्टल, ऋण गेटवे और ग्रामीण ऋण नेटवर्क तक सीधी पहुंच।',
    quickLinksCatReportsTitle: 'PMMY रिपोर्ट',
    quickLinksCatReportsSubtitle: 'वित्तीय प्रदर्शन',
    quickLinksCatReportsDesc: 'लेखा-परीक्षित वित्तीय प्रगति आंकड़े, राज्यवार ऋण वितरण और MLI प्रदर्शन मीट्रिक।',
    quickLinksCatDocumentsTitle: 'दस्तावेज़',
    quickLinksCatDocumentsSubtitle: 'आधिकारिक प्रकाशन',
    quickLinksCatDocumentsDesc: 'आधिकारिक परिपत्र, कॉफी टेबल बुक्स, MSME नीति ढांचे और सफलता की कहानियों के संग्रह।',
    quickLinksCatEventsTitle: 'कार्यक्रम एवं मीडिया',
    quickLinksCatEventsSubtitle: 'दृश्य झलकियां',
    quickLinksCatEventsDesc: 'प्रेस बुलेटिन, राष्ट्रीय ऋण मेलों की फोटो अभिलेख, और MSME पुरस्कार समारोह।',

    // ---- About MUDRA (AboutPMMY.jsx) ----
    aboutEyebrow: 'सिडबी की पूर्ण स्वामित्व वाली सहायक कंपनी',
    aboutTitle: 'मुद्रा एवं प्रधानमंत्री मुद्रा योजना के बारे में',
    aboutDescription: 'सूक्ष्म इकाई विकास एवं पुनर्वित्त एजेंसी लिमिटेड (मुद्रा) की स्थापना भारत सरकार द्वारा 8 अप्रैल, 2015 को गैर-कॉर्पोरेट, गैर-कृषि लघु एवं सूक्ष्म उद्यमों को ₹20 लाख तक की औपचारिक वित्तीय संस्थान ऋण सुविधा प्रदान करने के लिए की गई थी। मुद्रा एक सांविधिक पुनर्वित्त सेतु के रूप में कार्य करती है, जो बैंकों, MFI और NBFC को पूरे भारत में बिना जमानत ऋण देने के लिए सक्षम बनाती है।',
    aboutPillar1Title: 'पुनर्वित्त सहायता',
    aboutPillar1Desc: 'सूक्ष्म इकाइयों तक अंतिम छोर तक ऋण प्रवाह के लिए बैंकों, MFI और NBFC को कम लागत वाली पुनर्वित्त सहायता प्रदान करता है।',
    aboutPillar2Title: 'ऋण गारंटी योजना',
    aboutPillar2Desc: 'बिना जमानत ऋण सुनिश्चित करने के लिए CGFMU गारंटी कवर के माध्यम से ऋणदाता संस्थानों की सुरक्षा करता है।',
    aboutPillar3Title: 'मुद्रा कार्ड सुविधा',
    aboutPillar3Desc: 'परेशानी मुक्त तरल ऋण निकासी के लिए पूर्व-स्वीकृत कार्यशील पूंजी रुपे डेबिट कार्ड से ऋणियों को सशक्त बनाता है।',
    aboutPillar4Title: 'क्षमता एवं कौशल विकास',
    aboutPillar4Desc: 'प्रथम पीढ़ी के उद्यमियों को प्रशिक्षित, मार्गदर्शन और शामिल करने के लिए RSETI और EDP संस्थानों के साथ साझेदारी करता है।',
    aboutStepLabel: 'चरण',
    aboutStep1Title: 'मुद्रा सदस्य ऋणदाता संस्थानों को पुनर्वित्त प्रदान करती है',
    aboutStep1Desc: 'सिडबी की पूर्ण स्वामित्व वाली सहायक कंपनी मुद्रा, सूक्ष्म इकाइयों को आगे ऋण देने के लिए बैंकों, MFI और NBFC को कम लागत वाला पुनर्वित्त प्रदान करती है।',
    aboutStep2Title: 'सदस्य ऋणदाता मूल्यांकन एवं स्वीकृति करता है',
    aboutStep2Desc: 'MLI आपके व्यवसाय का आकलन करता है और PMMY दिशानिर्देशों के अनुसार शिशु, किशोर एवं तरुण श्रेणियों में बिना जमानत ऋण वितरित करता है।',
    aboutStep3Title: 'ऋण गारंटी सुरक्षा (CGFMU)',
    aboutStep3Desc: 'ऋण सूक्ष्म इकाइयों के लिए गारंटी फंड द्वारा समर्थित हैं, जिससे ऋणियों को तृतीय-पक्ष जमानत या गारंटी की आवश्यकता नहीं होती।',
    aboutStep4Title: 'पूरे भारत में एंड-टू-एंड डिजिटल पहुंच',
    aboutStep4Desc: 'ऋणी उद्यमीमित्र पोर्टल से जुड़े 1,500+ सदस्य ऋणदाता संस्थानों के माध्यम से आवेदन करते हैं, जो 700+ जिलों को कवर करते हैं।',

    // ---- Vision & Mission (VisionMission.jsx) ----
    visionMissionEyebrow: 'हमारा मार्गदर्शक दर्शन',
    visionMissionTitlePrefix: 'का विज़न एवं मिशन',
    visionMissionDescription: 'एक समावेशी, सुदृढ़ वित्तीय पारिस्थितिकी तंत्र का निर्माण जो पूरे भारत में सूक्ष्म-उद्यमिता और आर्थिक आत्मनिर्भरता को बढ़ावा देता है।',
    visionKicker: 'रणनीतिक दृष्टिकोण',
    visionTag: 'भविष्य का मानदंड',
    visionQuote: '"निम्न आय वर्ग के व्यापक आर्थिक एवं सामाजिक विकास के लिए वैश्विक सर्वोत्तम प्रथाओं एवं मानकों के अनुरूप एक उत्कृष्ट एकीकृत वित्तीय एवं सहयोग सेवा प्रदाता बनना।"',
    visionPillarsLabel: 'प्रमुख दृष्टिकोण चालक:',
    visionPillar1: 'एकीकृत वित्तीय सेवाएं',
    visionPillar2: 'वैश्विक सर्वोत्तम प्रथाएं',
    visionPillar3: 'निम्न आय वर्ग को सहयोग',
    visionPillar4: 'व्यापक सामाजिक विकास',
    visionFooterLeft: 'राष्ट्रीय मानक',
    visionFooterRight: 'निम्न आय वर्ग पर फोकस',
    missionKicker: 'कार्य उद्देश्य',
    missionTag: 'संस्थागत तालमेल',
    missionQuote: '"अपने भागीदार संस्थानों के सहयोग से आर्थिक सफलता एवं वित्तीय सुरक्षा प्राप्त करने हेतु एक समावेशी, संधारणीय एवं मूल्य-आधारित उद्यमशील संस्कृति का निर्माण करना।"',
    missionPillarsLabel: 'प्रमुख मिशन स्तंभ:',
    missionPillar1: 'समावेशी उद्यम संस्कृति',
    missionPillar2: 'भागीदार संस्थान तालमेल',
    missionPillar3: 'संधारणीय वित्तीय सुरक्षा',
    missionPillar4: 'मूल्य-आधारित सशक्तिकरण',
    missionFooterLeft: 'भागीदार संस्थान',
    missionFooterRight: 'वित्तीय सुरक्षा',

    // ---- Loan Products (LoanProducts.jsx) ----
    loanProductsEyebrow: 'वर्गीकृत ऋण श्रेणियां',
    loanProductsTitle: 'PMMY योजनाओं का अवलोकन एवं श्रेणियां',
    loanProductsDescription: 'मुद्रा ऋणों को चार अनुकूलित श्रेणियों में वर्गीकृत करती है। पूर्ण पात्रता, ब्याज दरें, आवश्यक दस्तावेज़ और आवेदन जानकारी देखने के लिए किसी भी योजना कार्ड पर क्लिक करें।',
    loanProductsCollateralFree: 'बिना जमानत PMMY ऋण सुविधा',
    loanProductsViewInfo: 'जानकारी देखने और आवेदन के लिए क्लिक करें',
    loanProductShishuStage: 'नए एवं सूक्ष्म शुरुआतकर्ता',
    loanProductShishuRange: '₹50,000/- तक का ऋण',
    loanProductShishuDesc: 'प्रारंभिक चरण के सूक्ष्म उद्यमियों, छोटे शिल्पकारों, फेरीवालों और अपना कारोबार शुरू कर रहे दुकानदारों के लिए तैयार किया गया।',
    loanProductKishoreStage: 'बढ़ती सूक्ष्म इकाइयां',
    loanProductKishoreRange: '₹50 हज़ार से ऊपर एवं ₹5 लाख तक',
    loanProductKishoreDesc: 'कार्यशील पूंजी, मशीनरी खरीद, इन्वेंट्री विस्तार या व्यवसाय आधुनिकीकरण चाहने वाले मौजूदा व्यवसाय मालिकों के लिए उपयुक्त।',
    loanProductTarunStage: 'स्थापित उद्यम',
    loanProductTarunRange: '₹5 लाख से ऊपर एवं ₹10 लाख तक',
    loanProductTarunDesc: 'परिचालन विस्तार, तकनीक उन्नयन, व्यापार मात्रा बढ़ाने या वाणिज्यिक वाहन खरीदने वाले स्थापित लघु व्यवसायों के लिए अनुकूलित।',
    loanProductTarunPlusStage: 'दोहराव पात्र ऋणी',
    loanProductTarunPlusRange: '₹10 लाख से ऊपर एवं ₹20 लाख तक',
    loanProductTarunPlusDesc: 'केंद्रीय बजट मुद्रा 2.0 पहल जो पूर्व तरुण ऋण को स्वच्छ रिकॉर्ड के साथ सफलतापूर्वक चुका चुके दोहराव ऋणियों के लिए सीमा दोगुनी करती है।',

    // ---- Loan Journey (LoanJourney.jsx) ----
    loanJourneyEyebrow: 'आपकी मुद्रा यात्रा',
    loanJourneyTitle: 'खोज से वितरण तक — हर कदम पर मार्गदर्शन',
    loanJourneyDescription: 'पात्रता जांचने से लेकर अपने स्वीकृत ऋण को ट्रैक करने तक एक ही जुड़ा हुआ मार्ग — हर चरण सीधे संबंधित मुद्रा सेवा से जुड़ा है।',
    loanJourneyStep1Title: 'पात्रता जांचें',
    loanJourneyStep1Desc: 'शिशु, किशोर, तरुण एवं तरुण-प्लस के लिए पात्रता, ऋण सीमा और आवश्यक दस्तावेज़ देखें।',
    loanJourneyStep1Cta: 'पात्रता देखें',
    loanJourneyStep2Title: 'योजना चुनें',
    loanJourneyStep2Desc: 'चारों PMMY श्रेणियों की तुलना करें और अपने व्यवसाय चरण से मेल खाने वाली योजना चुनें।',
    loanJourneyStep2Cta: 'योजनाओं की तुलना करें',
    loanJourneyStep3Title: 'आवेदन करें',
    loanJourneyStep3Desc: 'निर्देशित ऑनबोर्डिंग शुरू करें, या सीधे आधिकारिक जनसमर्थ पोर्टल के माध्यम से आवेदन करें।',
    loanJourneyStep3Cta: 'आवेदन शुरू करें',
    loanJourneyStep3SecondaryCta: 'जनसमर्थ के माध्यम से आवेदन करें',
    loanJourneyStep4Title: 'आवेदन ट्रैक करें',
    loanJourneyStep4Desc: 'अपने आवेदन की स्थिति, सत्यापन और वितरण को वास्तविक समय में देखें।',
    loanJourneyStep4Cta: 'स्थिति ट्रैक करें',

    // ---- Success Stories Carousel (SuccessStoriesCarousel.jsx) ----
    successCarouselEyebrow: 'जमीनी स्तर की प्रेरणा',
    successCarouselTitle: 'PMMY सफलता की कहानियां',
    successCarouselDescription: 'बिना जमानत मुद्रा ऋण से सशक्त हुए जमीनी स्तर के उद्यमियों, महिला नेताओं और ग्रामीण नवप्रवर्तकों की वास्तविक कहानियां। कहानी पढ़ने के लिए कार्ड पर होवर करें।',
    successCarouselExploreAll: 'सभी कहानियां देखें',
    successCarouselReadFull: 'पूरी कहानी पढ़ें',
    successCarouselImpact: 'प्रभाव',

    // ---- Fraud & Safety Center (FraudSafetyCenter.jsx) ----
    fraudEyebrow: 'धोखाधड़ी एवं सुरक्षा केंद्र',
    fraudTitle: 'सुरक्षित रहें — मुद्रा एजेंटों के माध्यम से कभी शुल्क नहीं लेती',
    fraudDescription: 'हर PMMY आवेदक के लिए आधिकारिक सांविधिक सलाह। यदि मुद्रा का प्रतिनिधित्व करने का दावा करने वाला कोई व्यक्ति आपसे कभी भुगतान मांगे, तो यह धोखाधड़ी है।',
    fraudSafeguard1Title: 'कोई एजेंट या बिचौलिया नहीं',
    fraudSafeguard1Desc: 'मुद्रा ने कोई एजेंट या सुविधाकर्ता नियुक्त नहीं किया है। स्वयं को आधिकारिक मुद्रा प्रतिनिधि बताने वाले धोखेबाजों से सावधान रहें।',
    fraudSafeguard2Title: 'केवल आधिकारिक माध्यमों से आवेदन करें',
    fraudSafeguard2Desc: 'मुद्रा एक पुनर्वित्त संस्था है और व्यक्तियों को सीधे ऋण नहीं देती। ऋणी सदस्य ऋणदाता संस्थानों (बैंक, MFI, NBFC) के माध्यम से या आधिकारिक उद्यमीमित्र पोर्टल पर ऑनलाइन आवेदन कर सकते हैं।',
    fraudSafeguard3Title: 'व्यक्तियों को कभी प्रोसेसिंग शुल्क न दें',
    fraudSafeguard3Desc: 'ऋणियों को सख्त सलाह दी जाती है कि वे स्वयं को आधिकारिक मुद्रा सुविधाकर्ता बताने वाले व्यक्तियों को कोई पैसा या प्रोसेसिंग शुल्क न दें।',
    fraudReportLabel: 'धोखाधड़ी का संदेह है? तुरंत रिपोर्ट करें',
    fraudReportDesc: 'नीचे दिए गए आधिकारिक हेल्पडेस्क या टोल-फ्री हेल्पलाइन पर संपर्क करें, या संपर्क पृष्ठ के माध्यम से पहुंचें — मुद्रा की ओर से भुगतान मांगने वाले किसी भी व्यक्ति से न जुड़ें।',
    fraudReportCta: 'धोखाधड़ी की रिपोर्ट करें',

    // ---- Announcements & News (AnnouncementsNews.jsx) ----
    newsEyebrow: 'आधिकारिक बुलेटिन एवं सूचनाएं',
    newsTitle: 'घोषणाएं एवं ताज़ा समाचार',
    newsDescription: 'मुद्रा से सीधे आधिकारिक प्रेस विज्ञप्तियों, सरकारी परिपत्रों, सांविधिक सतर्कता चेतावनियों और नीति दिशानिर्देशों से अपडेट रहें।',
    newsTabPress: 'प्रेस समाचार',
    newsTabCirculars: 'आधिकारिक परिपत्र',
    newsTabAdvisories: 'सांविधिक सलाह',
    newsAdvisoryLabel: 'सांविधिक सलाह:',
    newsAdvisoryText: 'मुद्रा कोई अग्रिम प्रोसेसिंग शुल्क नहीं लेती और न ही बिचौलिए एजेंट नियुक्त करती है। हमेशा सीधे बैंकों या जनसमर्थ पोर्टल के माध्यम से आवेदन करें',
    newsReadCircular: 'परिपत्र पढ़ें',

    // ---- Social Media Feed (SocialMediaFeed.jsx) ----
    socialEyebrow: 'रीयल-टाइम सोशल कनेक्ट',
    socialTitle: 'मुद्रा लाइव सोशल मीडिया हब',
    socialDescription: 'मुद्रा इंडिया के सत्यापित सोशल चैनलों से सीधे आधिकारिक घोषणाओं, वीडियो, सफलता की कहानियों एवं नीति अपडेट के साथ जुड़े रहें।',
    socialTabAll: 'सभी फ़ीड',
    socialTrendingTopics: 'ट्रेंडिंग विषय:',
    socialClearFilter: 'फ़िल्टर हटाएं',
    socialNoPosts: 'चयनित फ़िल्टर से मेल खाने वाली कोई पोस्ट नहीं है।',
    socialViewPost: 'पोस्ट देखें',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};